### ISSUE TITLE
Incorporating Crazyenvoys.

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/battle-pass#170]
This issue was reported by Mocked#6959 | 208314944683376642

Discord [Transcript](https://tickettool.xyz/direct?url=https://cdn.discordapp.com/attachments/839378013346725888/973408298088939540/transcript-gc-battlepass-crazyenvoys.html)

"im incorporating crazy envoys into battlepass
the file path is not me/badbones69 its com/badbones69
com/badbones69"
![image](https://user-images.githubusercontent.com/63577950/167529173-a737612a-7d6d-44b6-bd60-5abf007ca0f1.png)

**Comment by GC-spigot** [comment]
Fixed

**Comment by flogna** [comment]
Senior Moderator | Jben said to leave a comment saying you did not fix it. Thank you. 
![image](https://user-images.githubusercontent.com/36687137/211132050-92e51f07-3223-4dc5-bd3f-74be3d98c4e0.png)

**Comment by Awpmeister2170** [comment]
Reopened due to issue not currently fixed

**Comment by Superalex0102** [comment]
Still not fixed @GC-spigot
