### ISSUE TITLE
Chatreaction: ERROR]: Could not pass event ReactionWinEvent to BattlePass v4.4.8

### ISSUE THREAD

**Issue by ISN-Bulma** [GC-spigot/battle-pass#582]
### Describe the bug

When you play chatreaction a new error message has shown up ever since we updated.
When playing the chat reaction and a player wins the game a long message gets sent out: [ERROR]: Could not pass event ReactionWinEvent to BattlePass v4.4.8

### How to reproduce

have a chatreaction quest and win a chatreaction.

### Screenshots / Videos

https://i.gyazo.com/7084500d5da0fd898a5dc69246c3a8d8.mp4

### Server Log

https://mcpaste.io/a26ec31a4c22ebff

**Comment by KPGTB** [comment]
Hey! Please update plugin to the latest version. It should fix this problem

**Comment by ISN-Bulma** [comment]
> Hey! Please update plugin to the latest version. It should fix this problem

I updated Battlepass to newest version, but the Error remains.

**Comment by KPGTB** [comment]
Hey! Fix will be available in the next update

**Comment by ISN-Bulma** [comment]
Thank you

**Comment by ISN-Bulma** [comment]
Any updates?

**Comment by KPGTB** [comment]
Hey! It should be already fixed. Please check the latest version of BattlePass
